# Generated by Django 4.0.2 on 2022-03-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('price', models.PositiveIntegerField(blank=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images_product')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='productscategory',
            name='name',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
